apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-auth
spec:
  replicas: 1
  selector:
    matchLabels: 
      backend: auth
  template: 
    metadata:
      labels:
        backend: auth
    spec:
      containers:
        - name: backend-auth
          image: kalax1011/auth
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: service-auth
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector: 
    backend: auth

