apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-checkout
spec:
  replicas: 1
  selector:
    matchLabels: 
      backend: checkout
  template: 
    metadata:
      labels:
        backend: checkout
    spec:
      containers:
        - name: backend-checkout
          image: kalax1011/checkout
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: service-checkout
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector: 
    backend: checkout

