apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-product
spec:
  replicas: 1
  selector:
    matchLabels: 
      backend: product
  template: 
    metadata:
      labels:
        backend: product
    spec:
      containers:
        - name: backend-product
          image: kalax1011/product
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: service-product
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector: 
    backend: product

