apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-microservices
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: service-auth
            port:
              number: 80
      - path: /product
        pathType: Prefix
        backend:
          service:
            name: service-product
            port:
              number: 80
      - path: /checkout
        pathType: Prefix
        backend:
          service:
            name: service-checkout
            port:
              number: 80